# to use this add docker-compose/mailcatcher.override.yml
# to your COMPOSE_FILE var in .env

services:
  web:
    links:
      - mailcatcher

  mailcatcher:
    image: instructure/mailcatcher
    environment:
      VIRTUAL_HOST: mail.canvas.docker
      VIRTUAL_PORT: 8080
    networks:
      canvas_network:
        ipv4_address: 172.16.1.8

networks:
  canvas_network:
    external: true
    name: canvas_network